# Generated by Django 4.1.2 on 2022-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song", name="audio", field=models.FileField(upload_to="music"),
        ),
    ]
